name: Easter at Palmcroft
favicon: null
layout_spectrum: 0.89754
typography_spectrum: 0.8539306398015469
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f1e8'
    - '#549d75'
    - '#413f40'
    - '#fae54f'
    - '#b0ab9c'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
