name: Easter at Palmcroft
favicon: null
layout_spectrum: 0.50155
typography_spectrum: 0.8539306398015469
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f1e8'
    - '#549d75'
    - '#413f40'
    - '#fae54f'
    - '#b0ab9c'
  brandStrength: 0.8611674520652741
  lightness: 0.21985876420512795
  saturation: 0.534188951831311
  rhythmicContrast: 0.1267242431640625
purpose: []
